version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # Porta padrão do RabbitMQ
      - "15672:15672" # Porta de gerenciamento do RabbitMQ (UI)
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - "./data:/var/lib/rabbitmq" # Persistência dos dados
